### ISSUE TITLE
fallback timestamp function ms precision

### ISSUE THREAD

**Issue by rho24** [wavded/graygelf#12]
Hi
Due to limitations with our build system our usage of graygelf falls back to the [non-microtime timestamp function](https://github.com/wavded/graygelf/blob/4ec5642142121ea03f39e1f50b06feae2f858755/index.js#L14). This works as designed however we noticed that the precision of the timestamps are seconds.

I was wondering if there is a reason it is limited to seconds? If not then I'd be happy to send a pull request to up the precision to milliseconds.

Regards
Richard

**Comment by wavded** [comment]
I don't believe there was a reason as far as I recall.  A PR would be welcome.

**Comment by rho24** [comment]
Thanks @wavded. I've confirmed the fix works in 1.0.2 in our codebase. Is it likely to be published to npm soon?

**Comment by wavded** [comment]
@rho24 that has been published on npm, does that version not work?

I noticed the npmjs site is out of date for some reason:

https://www.npmjs.com/package/graygelf

However `npm info graygelf` shows the latest has been published.

**Comment by rho24** [comment]
My mistake, i got as far as npmjs and assumed it hadn't been published!
The npm cli picks up 1.0.2 and all works as expected.

Thanks very much!
