### ISSUE TITLE
Question about the server

### ISSUE THREAD

**Issue by Evertvdw** [wavded/graygelf#24]
Hi there, is it possible to use the server as an endpoint to which I could send stuff from the browser so that I can send it on to Graylog from there? It is unclear to me how to use this at the moment. 

I tried this from the examples:
```
	var gelfserver = require("graygelf/server");
	var server = gelfserver();
	server.on("message", function(gelf) {
		// handle parsed gelf json
		console.log("received message", gelf.short_message);
	});
	server.listen(12201);
```

How can I access that server then? Doing a POST with json data to "http://localhost:12201" does not seem to work.

**Comment by wavded** [comment]
> Hi there, is it possible to use the server as an endpoint to which I could send stuff from the browser so that I can send it on to Graylog from there? 

@Evertvdw Not directly. The server in this library is a server specifically designed for the client, so its UDP, not TCP and won't work with an HTTP POST. It allows you to receive client requests and do stuff with them (like proxy, make changes, log them, etc.). You'd need to write your own HTTP server and just use the client directly if you wanted to do a POST with JSON data.

**Comment by Evertvdw** [comment]
Ok, clear enough, thanks!
