### ISSUE TITLE
Added typings for typescript in DefinitelyTyped

### ISSUE THREAD

**Issue by DavidProf** [wavded/graygelf#25]
I am just really hoping that someone can review the typing added in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47332/files) (repo to add typescript types apart), and help to reach their approval.

**Comment by wavded** [comment]
@DavidProf I see you got this merged. Great! I would be up for including types right in this project as well in the future. If you feel inspired, you are welcome to open a PR here.

**Comment by DavidProf** [comment]
No Reasons to keep this open, right?
